{{- with index .Values "cluster-configs" "secrets" "egov-user" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name | default "egov-user" }}
  namespace: egov
type: Opaque
data:
  secretkey: {{ index . "secret-key" | b64enc | quote }}
  secretalgorithm: {{ index . "secret-algorithm"  | b64enc | quote }}
  secrettransformation: {{ index . "secret-transformation"  | b64enc | quote }}
{{- end }}
